version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=control2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend-c2
    container_name: backend-c2
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/control2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend-c2
    container_name: frontend-c2
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - "3000:3000"

volumes:
  pgdata: